---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu 
    driver:
      box: ubuntu-16.04
      box_url: http://192.168.10.184/software/ubuntu-16.04-amd64.box
      network:
        - ['public_network', bridge: 'en0: Wi-Fi (AirPort)']

suites:
  - name: default
    run_list:
      - recipe[tftpd_server::default]
    attributes:
